### ISSUE TITLE
Arduino IDE can't find library

### ISSUE THREAD

**Issue by UncannyBingo** [sparkfun/SparkFun_TLC5940_Arduino_Library#1]
After cloning the git repo into ~/Documents/Arduino/libraries (on a Mac. This is how I install most Arduino libraries) the library fails to appear in the Arduino IDE. Is there something different that must be done with this library?

**Comment by ToniCorinne** [comment]
There was a space in the library.properties file that breaks the IDE library manager functionality. It's been fixed now and should work for you. Let us know if you have any other problems!
