### ISSUE TITLE
Issue with the file naming convention 

### ISSUE THREAD

**Issue by dastergon** [sparkfun/SparkFun_TLC5940_Arduino_Library#2]
Hi there, 

Happy New Year! I am Pavlos from codebender.

Recently we tried to add this library in codebender supported libraries but we had some issues with the filenames. The library's name does not have SparkFun prepended like other SparkFun libraries. This causes a name collision with other libraries that we currently support. If you prepend SparkFun to the filenames (e.g: `Tlc5940.h` -> `SparkFun_Tlc5940.h`) it would help us resolve these conflicts.

Thanks,
Pavlos

**Comment by ToniCorinne** [comment]
Hi @dastergon - I updated the names and pushed the changes. Please let me know if there's anything else we can do to assist you with this. 

Thanks!
