### ISSUE TITLE
TLC with Arduino Mega

### ISSUE THREAD

**Issue by alequeiroz** [sparkfun/SparkFun_TLC5940_Arduino_Library#3]
To use the library in Arduino mega what are the changes needed to be made? the code needs to be changed or it automatically recog?

**Comment by ToniCorinne** [comment]
Take a look at the [tlc_config.h](https://github.com/sparkfun/SparkFun_TLC5940_Arduino_Library/blob/master/src/tlc_config.h) file. This describes a lot of the pin mapping, and should get you moving forward.

Line 67 also discusses what lines need to be updated for custom SPI pin selection.
