### ISSUE TITLE
Digital Pin D12 held high after Tlc.init() 

### ISSUE THREAD

**Issue by Cyrilanthony777** [sparkfun/SparkFun_TLC5940_Arduino_Library#7]
Digital Pin D12 is not responding after Tlc.init(). XERR_ENABLED is set to 0

**Comment by Grahldg** [comment]
Hello.  D12 (the default XERR pin) is disabled unless XERR_ENABLED is set to 1.  XERR_ENABLED is a constant defined on [line 16](https://github.com/sparkfun/SparkFun_TLC5940_Arduino_Library/blob/master/src/tlc_config.h#L116) of [tlc_config.h](https://github.com/sparkfun/SparkFun_TLC5940_Arduino_Library/blob/master/src/tlc_config.h).

You can find this file in your local library by going to the Arduino directory for your local user which is typically at **Users/_UserName_/Documents/Arduino/Sparkfun_TLC5940_Arduino/src** in Windows and OSX.  After changing the 0 to a 1 on line 116 you might need to delete **tlc5940.o** from the same directory (if it exists).

If you're still having issues you can get more immediate help by contacting our [Technical Support Team](https://www.sparkfun.com/technical_assistance).
